export const tooling = {
  regular: {
    languages: ["HTML", "CSS", "JavaScript", "TypeScript", "C#", "SQL"],
    frameworks: ["React", "Tailwind CSS", "ASP.NET Core"],
    libraries: [
      "TanStack",
      "React Hook Form",
      "Zod",
      "FluentValidation",
      "OpenLayers",
    ],
    ui: ["Ark-ui", "Radix-ui", "Headless UI", "React Aria", "Shadcn/ui"],
    databases: ["PostgreSQL"],
    tests: ["Vitest", "Playwright", "XUnit", "Testcontainers"],
    tools: ["Vite", "Git", "Github", "Docker", "Vim", "VS Code", "Terminal"],
  },
  occasional: {
    languages: ["Go", "Lua", "Python", "Java", "C++"],
    frameworks: [
      "Astro",
      "Next.js",
      "Angular",
      "SolidJS",
      "Blazor",
      "PandaCSS",
    ],
    libraries: [
      "XState",
      "RxJS",
      "Redux",
      "Zustand",
      "Maplibre",
      "Mapbox",
      "Sanity",
    ],
    ui: ["Chakra UI", "ParkUI", "RizzUI", "Justd"],
    databases: ["SQL Server", "SQLite", "MongoDB"],
    tests: ["Jest", "Cypress"],
    tools: ["Rolldown", "RSPack", "NeoVim", "Visual Studio", "Figma"],
  },
};
